---
- hosts : mygroup:localhost
  serial: 1
  max_fail_percentage: 100
  vars: 
    header: "Welcome to Ansible World"
    footer: "- Wells Fargo"
    author: "Abhishek Garg"
  tasks:
  - name: getting uptime
    shell: "uptime | awk '{print $3}' | sed 's/,//g'"
    register: server_uptime
    tags:
    - getuptime

  - name: print server_uptime
    debug:
      msg: "{{ server_uptime }}"
    tags:
    - prnuptime

  - name: generate banner
    template:
      src: '/etc/ansible/playbooks/motdsample.j2'
      dest: '/etc/motd'
    tags:
    - getbanner
